### ISSUE TITLE
RESP.app is now support extension with REST API

### ISSUE THREAD

**Issue by uglide** [javalover123/rdm-formatters#1]
Hello @javalover123 

Starting from 2022.4 RESP.app offers a much better alternative to "native formatters" https://docs.resp.app/en/latest/extension-server/

As described in docs, you can now quickly generate a Java boilerplate with OpenAPI generator. Feel free to ping me if you need any help with it or have any other feedback.

**Comment by javalover123** [comment]
@uglide https://github.com/javalover123/resp-app-extension-server

**Comment by uglide** [comment]
@javalover123 great! Let me know if you have any issues or feedback
